### ISSUE TITLE
support  CustomScrollView

### ISSUE THREAD

**Issue by ihihihihihihih** [rvamsikrishna/inview_notifier_list#11]
Is there a plan to support CustomScrollView ?

**Comment by rvamsikrishna** [comment]
It is in works. Having a problem with the gridviews being notified properly.

**Comment by rvamsikrishna** [comment]
@ihihihihihihih added support for CustomScrollView with the addition of `InViewNotifierCustomScrollView`. Updated the package to v1.0.0 to use it.
