### ISSUE TITLE
Get current index of the visible item

### ISSUE THREAD

**Issue by brizaldi** [rvamsikrishna/inview_notifier_list#13]
is there a way to get current index of the visible item, for example when the user press the button

**Comment by rvamsikrishna** [comment]
you already use `builder: (BuildContext context, int index) {}` to build your list items. Inside this builder using `InViewNotifierWidget` gives you the bool value whether the widget is in view. Use this bool to add/remove the current index to a List variable.

**Comment by rvamsikrishna** [comment]
@brizaldi I am closing the issue as there is no further response. Reopen it if you still have a doubt.
