### ISSUE TITLE
inView doesn't calculate until scrolled

### ISSUE THREAD

**Issue by skylerknight** [rvamsikrishna/inview_notifier_list#17]
Hi there,

This is a great plugin. Very useful. One problem that I've found is that the inView variable isn't calculated until the user scrolls the list. I'm making a reorderable drag & drop feature, and it would be nice if I could determine if an item is inView before the user actually begins to scroll.

**Comment by ManukumarSB** [comment]
> Hi there,
> 
> This is a great plugin. Very useful. One problem that I've found is that the inView variable isn't calculated until the user scrolls the list. I'm making a reorderable drag & drop feature, and it would be nice if I could determine if an item is inView before the user actually begins to scroll.

@skylerknight did you find any solution for this?

**Comment by zeiasoroush** [comment]
Any update on this?

**Comment by rvamsikrishna** [comment]
@skylerknight you can pass the id of the initial widget you want as in view to `initialInViewIds`

**Comment by rvamsikrishna** [comment]
@skylerknight Closing this issue. If doubt still exits please feel free to reopen.
