### ISSUE TITLE
Mute Video , Play and Pause.

### ISSUE THREAD

**Issue by ShrutiThakur01** [rvamsikrishna/inview_notifier_list#19]
Hi ,

I am using this plugin in my app and along with scrolling and inView play and pause  , i want to allow users to mute and play pause video. 
Play pause i want to give on longPress on video for mute i want to show icon.

How can i implement it in this plugin?

Thanks in advance.

**Comment by blunderous** [comment]
This package, as far as I know, does not aim to do that. In order to do that, you should use other packages that are dedicated to video controlls.

**Comment by rvamsikrishna** [comment]
@ShrutiThakur01 This package does not handle any video controls.
