### ISSUE TITLE
Does this works like listview or listview.builder?

### ISSUE THREAD

**Issue by anmolk25** [rvamsikrishna/inview_notifier_list#24]
I want to know its working because I have 100's of widget which I am currently displaying using listview builder as this is the best approach to optimise resources. I want to know if inview_notifier_list also works like a listview or listview.builder .

**Comment by vamsi-kleargroup** [comment]
@anmolk25 yes it works like a list view builder. It lazily renders the widget.

**Comment by rvamsikrishna** [comment]
> I want to know its working because I have 100's of widget which I am currently displaying using listview builder as this is the best approach to optimise resources. I want to know if inview_notifier_list also works like a listview or listview.builder .

Yes it lazily renders the list items just like `ListView.Builder`
