### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by whatamelon** [rvamsikrishna/inview_notifier_list#26]
I want to know you have plan for support null safety

**Comment by whatamelon** [comment]
@SedlarDavid Thx a lot!

**Comment by RalphMarvin** [comment]
@SedlarDavid where can i find your fork ?

**Comment by SedlarDavid** [comment]
> @SedlarDavid where can i find your fork ?

https://github.com/SedlarDavid/inview_notifier_list

**Comment by rvamsikrishna** [comment]
@whatamelon @CosmicPangolin the package has been updated to use the latest dependencies and null safety
