### ISSUE TITLE
Inview_notifier + betterplayer

### ISSUE THREAD

**Issue by threepat1** [rvamsikrishna/inview_notifier_list#33]
I want to precache video file to reduce bandwidth. any solutions? I find that betterplayer has function but I can't use with inview_notifier. got null error all times

**Comment by rvamsikrishna** [comment]
@threepat1 You can use any video player plugin with this package. This doesn't sound specific to this package. You can check out the video list example  [here](https://github.com/rvamsikrishna/inview_notifier_list/blob/master/example/lib/video_list.dart)
