### ISSUE TITLE
Implementation for NestedScrollView

### ISSUE THREAD

**Issue by CosmicPangolin** [rvamsikrishna/inview_notifier_list#34]
I think this is a pretty quick add, it would be nice to have in library :)

**Comment by rvamsikrishna** [comment]
@CosmicPangolin may I know what is the exact use case?

**Comment by CosmicPangolin** [comment]
@rvamsikrishna 

For various reasons related to header and nested page routing design, my app tree typically takes one of these two shapes:

```
NestedScrollView
     SliverAppBar
     SliverFixedExtentList
         Content
```

```
NestedScrollView
     SliverAppBar
     TabBarView
         ScrollView
              Content
```

For the second case using an existing implementation on the inner scrollview works fine, but for the first case I'm a bit stuck :)

**Comment by CosmicPangolin** [comment]
Sorry this was a confusion/mistake on my part :)
