### ISSUE TITLE
[Bug] Currently visible contexts are deleted in horizontal views

### ISSUE THREAD

**Issue by AlexanderFarkas** [rvamsikrishna/inview_notifier_list#38]
I've spotted, that some visible contexts are deleted, when:
1. user is scrolling fast
2. items are small

I removed 'removeContexts()' method, 'cause it seems culprit to me.
Instead I mark contexts 'removable', when I can't find them by 'findRenderObject'
@rvamsikrishna Check it out [here](https://github.com/AlexandrFarkas/inview_notifier_list/blob/3d43323d2dcd7233655535a8c076b3b57b4697b3/lib/src/inview_state.dart#L58)

Also I found InViewNotifier pretty useful for cases, where you would like to listen for 'inview' events outside of list. Kind of 'advanced usage'.

I've not made a pull request, 'cause these changes are untested and specific for my case. 
Maybe you will find something useful in my code to apply in your package)

**Comment by rvamsikrishna** [comment]
#45 has fixed this issue. Thank you very much for your time.😃
