### ISSUE TITLE
Unhandled Exception: Cannot get renderObject of inactive element.

### ISSUE THREAD

**Issue by getpu** [rvamsikrishna/inview_notifier_list#42]
In latest version 2.5.0 stable find new problem... 

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Cannot get renderObject of inactive element.
In order for an element to have a valid renderObject, it must be active, which means it is part of the tree.
Instead, this element is in the _ElementLifecycle.defunct state.
If you called this method from a State object, consider guarding it with State.mounted.
The findRenderObject() method was called for the following element:

**Comment by Eerey** [comment]
same

**Comment by sdegenaar** [comment]
Same

**Comment by Ebrahimhammad** [comment]
Same

**Comment by okursoftware** [comment]
Can anyone find a solution ?

**Comment by getpu** [comment]
No, only debug mode, build apk is normal work...

**Comment by Borr1310** [comment]
Any solutions?

**Comment by itadminmynapse** [comment]
me too

**Comment by dfdgsdfg** [comment]
https://github.com/flutter/flutter/issues/89902

**Comment by dfdgsdfg** [comment]
Maybe we have a different case. In my case, works just properly.

Did you try like below in the Pubspec?
```yaml
  inview_notifier_list:
    git:
      url: https://github.com/dfdgsdfg/inview_notifier_list.git
```

**Comment by CosmicPangolin** [comment]
@rvamsikrishna Any chance we can get the above fix released as a quick 2.0.1?

**Comment by ZaidrazaNarsinh** [comment]
Any update?

**Comment by inc16sec** [comment]
> Any update?

Here.. change your dependency on pubscpec.yaml to

 `inview_notifier_list:
    git:
      url: https://github.com/SteepSheep/inview_notifier_list.git`

**Comment by rikai-trongpq** [comment]
> > Any update?
> 
> Here.. change your dependency on pubscpec.yaml to
> 
> ```yaml
> inview_notifier_list:
>    git:
>      url: https://github.com/SteepSheep/inview_notifier_list.git
> ```

I confirm this not working. Any solution?

**Comment by rvamsikrishna** [comment]
@rikai-trongpq The package has been updated to `v3.0.0`. This is fixed

**Comment by rikai-trongpq** [comment]
> @rikai-trongpq The package has been updated to `v3.0.0`. This is fixed

I used to latest version but I still getting an error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Cannot get renderObject of inactive element.
E/flutter (25993): In order for an element to have a valid renderObject, it must be active, which means it is part of the tree.
E/flutter (25993): Instead, this element is in the _ElementLifecycle.defunct state.
E/flutter (25993): If you called this method from a State object, consider guarding it with State.mounted.
E/flutter (25993): The findRenderObject() method was called for the following element:
E/flutter (25993):   StatefulElement#00231(DEFUNCT)
```

**Comment by rikai-trongpq** [comment]
@getpu  Any update?

**Comment by fixry510** [comment]
flutter clean will slove this issue!
