### ISSUE TITLE
Null check error in InViewNotifierCustomScrollView

### ISSUE THREAD

**Issue by SachinCodeMatrix** [rvamsikrishna/inview_notifier_list#48]
<img width="1347" alt="Screenshot 2021-12-20 at 2 03 24 PM" src="https://user-images.githubusercontent.com/80881563/146736858-ed58c21c-f484-4bee-a9e5-76b779756e4c.png">

**Comment by FranciscoVenegas** [comment]
After many attempts, in my case I solved it by wrapping my video widget inside "InViewNotifierWidget" and using the "isInView" property. This and based on the "example" since my code was based on a very old version and that was not nullsafety.

I hope it works for you too.

**Comment by SachinCodeMatrix** [comment]
Thank you @FranciscoVenegas.
