### ISSUE TITLE
quickly drag up and down cause bug

### ISSUE THREAD

**Issue by iptton** [rvamsikrishna/inview_notifier_list#5]
quickly drag up and down may cause bug.
seems the problem happen because of stream transformer ?

**Comment by rvamsikrishna** [comment]
What is the bug you are encountering?

**Comment by iptton** [comment]
@rvamsikrishna 
I have upload an integration test case , you can run that test to reproduce the problem.
In brief: when scroll up and down for times(more than 10), than all views should "In View" being "not in view"

**Comment by iptton** [comment]
![unnamed](https://user-images.githubusercontent.com/97447/70420056-c4152b80-1aa1-11ea-858d-03ebc97fcb82.gif)
the PR #6  screenshot here

**Comment by rvamsikrishna** [comment]
Thank you @iptton for providing the integration test and the screenshot.

I am currently not on my computer. Can you check if this is happening after reducing the denounce duration? Do it if you are free or I'll check it out later.

**Comment by rvamsikrishna** [comment]
@iptton I tried running the integration test you provided. But could not run them successfully as there were not `key`'s added with value `ValueKey('item-1')` or `ValueKey('item-2')`.

**Comment by iptton** [comment]
@rvamsikrishna maybe you need to  modify  box.dart to add key, and don't forget to add list1 to the list
1  example/lib/box.dart 
```
@@ -23,6 +23,7 @@ class Box extends StatelessWidget {
          color: isInView ? Colors.lightGreen : Colors.amber,
          child: Text(
            '$id : $inViewTxt',
            key: ValueKey("item-$id"),
            style: Theme.of(context).textTheme.display1,
          ),
        );
```

---
I've tried removing throttle code, but it still not run correctly.

**Comment by iptton** [comment]
@rvamsikrishna 
hi ~ I've fix the bug . see the #6  commit logs

**Comment by rvamsikrishna** [comment]
@iptton Thank you. I'll check it out and make the changes.
