### ISSUE TITLE
Not working when having ListView as one of the Children widget

### ISSUE THREAD

**Issue by sahilkis** [rvamsikrishna/inview_notifier_list#8]
I have a screen where I was using SingleChildScrollView and inside it I have multiple ListViews. Now to implement this library I just put all the children widgets of SingleChildScrollView into InViewNotifierList children widget list.

It works fine if I didn't have any ListView inside children widgets list but when I put a ListView it somehow always assume that ListView starts from top of screen regardless of views that are present above it. That means it gives multiple views same time and inside inViewList.

If I use Column instead of ListView, then it works fine but that isn't appropriate from user experience point of view.

Any help regarding this issue will be appreciated.

Thanks

**Comment by rvamsikrishna** [comment]
Can you post a short code snippet of what you are trying to achieve? Is it having multiple listviews inside `InViewNotifierList`

**Comment by rvamsikrishna** [comment]
@sahilkis  Can you post a short code snippet of what you are trying to achieve? Is it having multiple listviews inside `InViewNotifierList`

**Comment by sahilkis** [comment]
Yes, I have multiple listviews inside InViewNotifierList but even if I try it with one Container with some height and one listview, it still gives the same issue.

**Comment by rvamsikrishna** [comment]
@sahilkis `InviewNotifierList` is intended to be used as normal ListView. Instead of having multiple `ListView`s inside `InViewNotifierList`, why not use multiple `InViewNotifierList`s

**Comment by rvamsikrishna** [comment]
Closing the issue as no further reply.
