### ISSUE TITLE
Pause video when i scroll 

### ISSUE THREAD

**Issue by AdnanKazi** [rvamsikrishna/inview_notifier_list#9]
Hey there,

Just wanted to know how do i pause those video which are not active 
For now in the given example of video there is a widget which uses future builder but i don't want to initialize every video when i scroll please let me know 

i am trying to implement feature like instagram when user scrolls video pause not re initialized please anyone have faced this problem please help me out

**Comment by rvamsikrishna** [comment]
@AdnanKazi Wrap your video widget with a custom `KeepAlive` widget as follows:
```
class KeepAlive extends StatefulWidget {
  const KeepAlive({Key key, this.child}) : super(key: key);

  final Widget child;

  @override
  _KeepAliveState createState() => _KeepAliveState();
}

class _KeepAliveState extends State<KeepAlive>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return widget.child;
  }
}
```

Check out the complete modified code for the video_list.dart file from the example folder in this [gist](https://gist.github.com/rvamsikrishna/13bbf462d68165fafb34e03eb37bbcef#file-video_list-dart-L65)

**Comment by AdnanKazi** [comment]
@rvamsikrishna thank you for fast response but your gist code throws an exception can i know where am i doing something wrong or what 

`'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1918 pos 15: 'keepAlive != null': is not true.
The relevant error-causing widget was: 
  AnimatedBuilder file:///Users/imac/Development/flutter-projects/innovate/lib/view/profile/profile_idea_list.dart:639:20`

**Comment by rvamsikrishna** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/31307345/76758208-47d06980-67af-11ea-9d8b-a3ba280207f9.gif)
@AdnanKazi  Its working fine for me

**Comment by AdnanKazi** [comment]
> ![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/31307345/76758208-47d06980-67af-11ea-9d8b-a3ba280207f9.gif)
> @AdnanKazi Its working fine for me

Okay then i will today itself at home and let you know If it works you will save my day  BTW thanks a lot for kindly response 😄

**Comment by AdnanKazi** [comment]
@rvamsikrishna Thank you so much it works perfectly.

**Comment by AdnanKazi** [comment]
@rvamsikrishna One more question can i set the quantity of videos to keep alive because as this method works fine in my device but to optimize memory storage there must be some procedure to release it

**Comment by AdnanKazi** [comment]
You code run perfectly on your example but it is not working in my project it throws an exception
` Failed assertion: line 1918 pos 15: 'keepAlive != null': is not true.`

**Comment by AdnanKazi** [comment]
Sorry My mistake There is already a class in flutter KeepAlive i just changed the name of Your class and it works

**Comment by Rafhan-hub** [comment]
@AdnanKazi please share your code, I have to used VisibilityDetetctor and also use keepAlive both are not working for me can you help me?
